/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReadyRouteImport } from './routes/ready'
import { Route as HealthRouteImport } from './routes/health'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AuthedOrgRouteImport } from './routes/_authed/org'
import { Route as AuthedMyRouteImport } from './routes/_authed/my'
import { Route as AuthedAdminRouteImport } from './routes/_authed/admin'
import { Route as AuthedOrgIndexRouteImport } from './routes/_authed/org/index'
import { Route as AuthedMyIndexRouteImport } from './routes/_authed/my/index'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as PublicAuthVerifyEmailRouteImport } from './routes/_public/auth/verify-email'
import { Route as AuthedOrgVerificationRouteImport } from './routes/_authed/org/verification'
import { Route as AuthedOrgRegisterRouteImport } from './routes/_authed/org/register'
import { Route as AuthedOrgProfileRouteImport } from './routes/_authed/org/profile'
import { Route as AuthedOrgPoliciesRouteImport } from './routes/_authed/org/policies'
import { Route as AuthedAdminVerificationsIndexRouteImport } from './routes/_authed/admin/verifications/index'
import { Route as AuthedOrgEventsNewRouteImport } from './routes/_authed/org/events/new'
import { Route as AuthedAdminVerificationsOrganizerIdRouteImport } from './routes/_authed/admin/verifications/$organizerId'
import { Route as AuthedOrgEventsEventIdConfigurePricingRouteImport } from './routes/_authed/org/events/$eventId/configure-pricing'
import { Route as AuthedOrgEventsEventIdConfigurePoliciesRouteImport } from './routes/_authed/org/events/$eventId/configure-policies'
import { Route as AuthedOrgEventsEventIdConfigureImagesRouteImport } from './routes/_authed/org/events/$eventId/configure-images'
import { Route as AuthedOrgEventsEventIdConfigureCategoriesRouteImport } from './routes/_authed/org/events/$eventId/configure-categories'

const ReadyRoute = ReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AuthedOrgRoute = AuthedOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMyRoute = AuthedMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrgIndexRoute = AuthedOrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedOrgRoute,
} as any)
const AuthedMyIndexRoute = AuthedMyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedMyRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const PublicAuthVerifyEmailRoute = PublicAuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => PublicRoute,
} as any)
const AuthedOrgVerificationRoute = AuthedOrgVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AuthedOrgRoute,
} as any)
const AuthedOrgRegisterRoute = AuthedOrgRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthedOrgRoute,
} as any)
const AuthedOrgProfileRoute = AuthedOrgProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedOrgRoute,
} as any)
const AuthedOrgPoliciesRoute = AuthedOrgPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AuthedOrgRoute,
} as any)
const AuthedAdminVerificationsIndexRoute =
  AuthedAdminVerificationsIndexRouteImport.update({
    id: '/verifications/',
    path: '/verifications/',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedOrgEventsNewRoute = AuthedOrgEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AuthedOrgRoute,
} as any)
const AuthedAdminVerificationsOrganizerIdRoute =
  AuthedAdminVerificationsOrganizerIdRouteImport.update({
    id: '/verifications/$organizerId',
    path: '/verifications/$organizerId',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedOrgEventsEventIdConfigurePricingRoute =
  AuthedOrgEventsEventIdConfigurePricingRouteImport.update({
    id: '/events/$eventId/configure-pricing',
    path: '/events/$eventId/configure-pricing',
    getParentRoute: () => AuthedOrgRoute,
  } as any)
const AuthedOrgEventsEventIdConfigurePoliciesRoute =
  AuthedOrgEventsEventIdConfigurePoliciesRouteImport.update({
    id: '/events/$eventId/configure-policies',
    path: '/events/$eventId/configure-policies',
    getParentRoute: () => AuthedOrgRoute,
  } as any)
const AuthedOrgEventsEventIdConfigureImagesRoute =
  AuthedOrgEventsEventIdConfigureImagesRouteImport.update({
    id: '/events/$eventId/configure-images',
    path: '/events/$eventId/configure-images',
    getParentRoute: () => AuthedOrgRoute,
  } as any)
const AuthedOrgEventsEventIdConfigureCategoriesRoute =
  AuthedOrgEventsEventIdConfigureCategoriesRouteImport.update({
    id: '/events/$eventId/configure-categories',
    path: '/events/$eventId/configure-categories',
    getParentRoute: () => AuthedOrgRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/health': typeof HealthRoute
  '/ready': typeof ReadyRoute
  '/admin': typeof AuthedAdminRouteWithChildren
  '/my': typeof AuthedMyRouteWithChildren
  '/org': typeof AuthedOrgRouteWithChildren
  '/org/policies': typeof AuthedOrgPoliciesRoute
  '/org/profile': typeof AuthedOrgProfileRoute
  '/org/register': typeof AuthedOrgRegisterRoute
  '/org/verification': typeof AuthedOrgVerificationRoute
  '/auth/verify-email': typeof PublicAuthVerifyEmailRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/my/': typeof AuthedMyIndexRoute
  '/org/': typeof AuthedOrgIndexRoute
  '/admin/verifications/$organizerId': typeof AuthedAdminVerificationsOrganizerIdRoute
  '/org/events/new': typeof AuthedOrgEventsNewRoute
  '/admin/verifications/': typeof AuthedAdminVerificationsIndexRoute
  '/org/events/$eventId/configure-categories': typeof AuthedOrgEventsEventIdConfigureCategoriesRoute
  '/org/events/$eventId/configure-images': typeof AuthedOrgEventsEventIdConfigureImagesRoute
  '/org/events/$eventId/configure-policies': typeof AuthedOrgEventsEventIdConfigurePoliciesRoute
  '/org/events/$eventId/configure-pricing': typeof AuthedOrgEventsEventIdConfigurePricingRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/health': typeof HealthRoute
  '/ready': typeof ReadyRoute
  '/org/policies': typeof AuthedOrgPoliciesRoute
  '/org/profile': typeof AuthedOrgProfileRoute
  '/org/register': typeof AuthedOrgRegisterRoute
  '/org/verification': typeof AuthedOrgVerificationRoute
  '/auth/verify-email': typeof PublicAuthVerifyEmailRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/my': typeof AuthedMyIndexRoute
  '/org': typeof AuthedOrgIndexRoute
  '/admin/verifications/$organizerId': typeof AuthedAdminVerificationsOrganizerIdRoute
  '/org/events/new': typeof AuthedOrgEventsNewRoute
  '/admin/verifications': typeof AuthedAdminVerificationsIndexRoute
  '/org/events/$eventId/configure-categories': typeof AuthedOrgEventsEventIdConfigureCategoriesRoute
  '/org/events/$eventId/configure-images': typeof AuthedOrgEventsEventIdConfigureImagesRoute
  '/org/events/$eventId/configure-policies': typeof AuthedOrgEventsEventIdConfigurePoliciesRoute
  '/org/events/$eventId/configure-pricing': typeof AuthedOrgEventsEventIdConfigurePricingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/health': typeof HealthRoute
  '/ready': typeof ReadyRoute
  '/_authed/admin': typeof AuthedAdminRouteWithChildren
  '/_authed/my': typeof AuthedMyRouteWithChildren
  '/_authed/org': typeof AuthedOrgRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/_authed/org/policies': typeof AuthedOrgPoliciesRoute
  '/_authed/org/profile': typeof AuthedOrgProfileRoute
  '/_authed/org/register': typeof AuthedOrgRegisterRoute
  '/_authed/org/verification': typeof AuthedOrgVerificationRoute
  '/_public/auth/verify-email': typeof PublicAuthVerifyEmailRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/my/': typeof AuthedMyIndexRoute
  '/_authed/org/': typeof AuthedOrgIndexRoute
  '/_authed/admin/verifications/$organizerId': typeof AuthedAdminVerificationsOrganizerIdRoute
  '/_authed/org/events/new': typeof AuthedOrgEventsNewRoute
  '/_authed/admin/verifications/': typeof AuthedAdminVerificationsIndexRoute
  '/_authed/org/events/$eventId/configure-categories': typeof AuthedOrgEventsEventIdConfigureCategoriesRoute
  '/_authed/org/events/$eventId/configure-images': typeof AuthedOrgEventsEventIdConfigureImagesRoute
  '/_authed/org/events/$eventId/configure-policies': typeof AuthedOrgEventsEventIdConfigurePoliciesRoute
  '/_authed/org/events/$eventId/configure-pricing': typeof AuthedOrgEventsEventIdConfigurePricingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/ready'
    | '/admin'
    | '/my'
    | '/org'
    | '/org/policies'
    | '/org/profile'
    | '/org/register'
    | '/org/verification'
    | '/auth/verify-email'
    | '/admin/'
    | '/my/'
    | '/org/'
    | '/admin/verifications/$organizerId'
    | '/org/events/new'
    | '/admin/verifications/'
    | '/org/events/$eventId/configure-categories'
    | '/org/events/$eventId/configure-images'
    | '/org/events/$eventId/configure-policies'
    | '/org/events/$eventId/configure-pricing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/ready'
    | '/org/policies'
    | '/org/profile'
    | '/org/register'
    | '/org/verification'
    | '/auth/verify-email'
    | '/admin'
    | '/my'
    | '/org'
    | '/admin/verifications/$organizerId'
    | '/org/events/new'
    | '/admin/verifications'
    | '/org/events/$eventId/configure-categories'
    | '/org/events/$eventId/configure-images'
    | '/org/events/$eventId/configure-policies'
    | '/org/events/$eventId/configure-pricing'
  id:
    | '__root__'
    | '/_authed'
    | '/_public'
    | '/health'
    | '/ready'
    | '/_authed/admin'
    | '/_authed/my'
    | '/_authed/org'
    | '/_public/'
    | '/_authed/org/policies'
    | '/_authed/org/profile'
    | '/_authed/org/register'
    | '/_authed/org/verification'
    | '/_public/auth/verify-email'
    | '/_authed/admin/'
    | '/_authed/my/'
    | '/_authed/org/'
    | '/_authed/admin/verifications/$organizerId'
    | '/_authed/org/events/new'
    | '/_authed/admin/verifications/'
    | '/_authed/org/events/$eventId/configure-categories'
    | '/_authed/org/events/$eventId/configure-images'
    | '/_authed/org/events/$eventId/configure-policies'
    | '/_authed/org/events/$eventId/configure-pricing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  HealthRoute: typeof HealthRoute
  ReadyRoute: typeof ReadyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ready': {
      id: '/ready'
      path: '/ready'
      fullPath: '/ready'
      preLoaderRoute: typeof ReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authed/org': {
      id: '/_authed/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof AuthedOrgRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/my': {
      id: '/_authed/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof AuthedMyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/org/': {
      id: '/_authed/org/'
      path: '/'
      fullPath: '/org/'
      preLoaderRoute: typeof AuthedOrgIndexRouteImport
      parentRoute: typeof AuthedOrgRoute
    }
    '/_authed/my/': {
      id: '/_authed/my/'
      path: '/'
      fullPath: '/my/'
      preLoaderRoute: typeof AuthedMyIndexRouteImport
      parentRoute: typeof AuthedMyRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_public/auth/verify-email': {
      id: '/_public/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof PublicAuthVerifyEmailRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authed/org/verification': {
      id: '/_authed/org/verification'
      path: '/verification'
      fullPath: '/org/verification'
      preLoaderRoute: typeof AuthedOrgVerificationRouteImport
      parentRoute: typeof AuthedOrgRoute
    }
    '/_authed/org/register': {
      id: '/_authed/org/register'
      path: '/register'
      fullPath: '/org/register'
      preLoaderRoute: typeof AuthedOrgRegisterRouteImport
      parentRoute: typeof AuthedOrgRoute
    }
    '/_authed/org/profile': {
      id: '/_authed/org/profile'
      path: '/profile'
      fullPath: '/org/profile'
      preLoaderRoute: typeof AuthedOrgProfileRouteImport
      parentRoute: typeof AuthedOrgRoute
    }
    '/_authed/org/policies': {
      id: '/_authed/org/policies'
      path: '/policies'
      fullPath: '/org/policies'
      preLoaderRoute: typeof AuthedOrgPoliciesRouteImport
      parentRoute: typeof AuthedOrgRoute
    }
    '/_authed/admin/verifications/': {
      id: '/_authed/admin/verifications/'
      path: '/verifications'
      fullPath: '/admin/verifications/'
      preLoaderRoute: typeof AuthedAdminVerificationsIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/org/events/new': {
      id: '/_authed/org/events/new'
      path: '/events/new'
      fullPath: '/org/events/new'
      preLoaderRoute: typeof AuthedOrgEventsNewRouteImport
      parentRoute: typeof AuthedOrgRoute
    }
    '/_authed/admin/verifications/$organizerId': {
      id: '/_authed/admin/verifications/$organizerId'
      path: '/verifications/$organizerId'
      fullPath: '/admin/verifications/$organizerId'
      preLoaderRoute: typeof AuthedAdminVerificationsOrganizerIdRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/org/events/$eventId/configure-pricing': {
      id: '/_authed/org/events/$eventId/configure-pricing'
      path: '/events/$eventId/configure-pricing'
      fullPath: '/org/events/$eventId/configure-pricing'
      preLoaderRoute: typeof AuthedOrgEventsEventIdConfigurePricingRouteImport
      parentRoute: typeof AuthedOrgRoute
    }
    '/_authed/org/events/$eventId/configure-policies': {
      id: '/_authed/org/events/$eventId/configure-policies'
      path: '/events/$eventId/configure-policies'
      fullPath: '/org/events/$eventId/configure-policies'
      preLoaderRoute: typeof AuthedOrgEventsEventIdConfigurePoliciesRouteImport
      parentRoute: typeof AuthedOrgRoute
    }
    '/_authed/org/events/$eventId/configure-images': {
      id: '/_authed/org/events/$eventId/configure-images'
      path: '/events/$eventId/configure-images'
      fullPath: '/org/events/$eventId/configure-images'
      preLoaderRoute: typeof AuthedOrgEventsEventIdConfigureImagesRouteImport
      parentRoute: typeof AuthedOrgRoute
    }
    '/_authed/org/events/$eventId/configure-categories': {
      id: '/_authed/org/events/$eventId/configure-categories'
      path: '/events/$eventId/configure-categories'
      fullPath: '/org/events/$eventId/configure-categories'
      preLoaderRoute: typeof AuthedOrgEventsEventIdConfigureCategoriesRouteImport
      parentRoute: typeof AuthedOrgRoute
    }
  }
}

interface AuthedAdminRouteChildren {
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
  AuthedAdminVerificationsOrganizerIdRoute: typeof AuthedAdminVerificationsOrganizerIdRoute
  AuthedAdminVerificationsIndexRoute: typeof AuthedAdminVerificationsIndexRoute
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
  AuthedAdminVerificationsOrganizerIdRoute:
    AuthedAdminVerificationsOrganizerIdRoute,
  AuthedAdminVerificationsIndexRoute: AuthedAdminVerificationsIndexRoute,
}

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(
  AuthedAdminRouteChildren,
)

interface AuthedMyRouteChildren {
  AuthedMyIndexRoute: typeof AuthedMyIndexRoute
}

const AuthedMyRouteChildren: AuthedMyRouteChildren = {
  AuthedMyIndexRoute: AuthedMyIndexRoute,
}

const AuthedMyRouteWithChildren = AuthedMyRoute._addFileChildren(
  AuthedMyRouteChildren,
)

interface AuthedOrgRouteChildren {
  AuthedOrgPoliciesRoute: typeof AuthedOrgPoliciesRoute
  AuthedOrgProfileRoute: typeof AuthedOrgProfileRoute
  AuthedOrgRegisterRoute: typeof AuthedOrgRegisterRoute
  AuthedOrgVerificationRoute: typeof AuthedOrgVerificationRoute
  AuthedOrgIndexRoute: typeof AuthedOrgIndexRoute
  AuthedOrgEventsNewRoute: typeof AuthedOrgEventsNewRoute
  AuthedOrgEventsEventIdConfigureCategoriesRoute: typeof AuthedOrgEventsEventIdConfigureCategoriesRoute
  AuthedOrgEventsEventIdConfigureImagesRoute: typeof AuthedOrgEventsEventIdConfigureImagesRoute
  AuthedOrgEventsEventIdConfigurePoliciesRoute: typeof AuthedOrgEventsEventIdConfigurePoliciesRoute
  AuthedOrgEventsEventIdConfigurePricingRoute: typeof AuthedOrgEventsEventIdConfigurePricingRoute
}

const AuthedOrgRouteChildren: AuthedOrgRouteChildren = {
  AuthedOrgPoliciesRoute: AuthedOrgPoliciesRoute,
  AuthedOrgProfileRoute: AuthedOrgProfileRoute,
  AuthedOrgRegisterRoute: AuthedOrgRegisterRoute,
  AuthedOrgVerificationRoute: AuthedOrgVerificationRoute,
  AuthedOrgIndexRoute: AuthedOrgIndexRoute,
  AuthedOrgEventsNewRoute: AuthedOrgEventsNewRoute,
  AuthedOrgEventsEventIdConfigureCategoriesRoute:
    AuthedOrgEventsEventIdConfigureCategoriesRoute,
  AuthedOrgEventsEventIdConfigureImagesRoute:
    AuthedOrgEventsEventIdConfigureImagesRoute,
  AuthedOrgEventsEventIdConfigurePoliciesRoute:
    AuthedOrgEventsEventIdConfigurePoliciesRoute,
  AuthedOrgEventsEventIdConfigurePricingRoute:
    AuthedOrgEventsEventIdConfigurePricingRoute,
}

const AuthedOrgRouteWithChildren = AuthedOrgRoute._addFileChildren(
  AuthedOrgRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRouteWithChildren
  AuthedMyRoute: typeof AuthedMyRouteWithChildren
  AuthedOrgRoute: typeof AuthedOrgRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRouteWithChildren,
  AuthedMyRoute: AuthedMyRouteWithChildren,
  AuthedOrgRoute: AuthedOrgRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicAuthVerifyEmailRoute: typeof PublicAuthVerifyEmailRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicAuthVerifyEmailRoute: PublicAuthVerifyEmailRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  HealthRoute: HealthRoute,
  ReadyRoute: ReadyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
